// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsvLMvUJK8jCk4syysR4C1_E88EOqq63g',
    appId: '1:507834994829:android:96e64c05671f3479de12c4',
    messagingSenderId: '507834994829',
    projectId: 'fir-login-f623d',
    storageBucket: 'fir-login-f623d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGfCYC8L3KZkuC2ToJBC99l9j96obp2QE',
    appId: '1:507834994829:ios:8e503c39763703a7de12c4',
    messagingSenderId: '507834994829',
    projectId: 'fir-login-f623d',
    storageBucket: 'fir-login-f623d.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGfCYC8L3KZkuC2ToJBC99l9j96obp2QE',
    appId: '1:507834994829:ios:8e503c39763703a7de12c4',
    messagingSenderId: '507834994829',
    projectId: 'fir-login-f623d',
    storageBucket: 'fir-login-f623d.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );
}
